### ISSUE TITLE
Jobs Board

### ISSUE THREAD

**Issue by Illizian** [NorfolkDev/norfolkdevelopers-website#23]
The creation of a Jobs Board, essentially following the same structure as Posts.

Additional to Posts these Jobs should have the following fields:

- Role Tag. e.g. Frontend, Backend, Full Stack, Mobile, Software, Data Science
- Salary
- Company
- Location
- Seniority
- Expiry Date

**Comment by tom-sherman** [comment]
@Illizian Hi! Would you accept a PR for this or are you already working on it?

**Comment by Illizian** [comment]
@tom-sherman we certainly would - thanks - I'll assign this issue to you :raised_hand_with_fingers_splayed:
