### ISSUE TITLE
Next event countdown timer

### ISSUE THREAD

**Issue by b1narylife** [NorfolkDev/norfolkdevelopers-website#46]
Maybe a nice little addition to the upcoming events section? Enhancement?

**Comment by Illizian** [comment]
Hey @b1narylife, I'm full of controversial opinions today but my knee jerk reaction is this may be a little tacky?

Perhaps I could be convinced by good design? :wink: this has made me wonder about adding "human readable" timestamps to the events though:

![image](https://user-images.githubusercontent.com/703800/92706250-45109480-f34c-11ea-93db-c34de5074ebe.png)

"Next Thursday at 7pm", "Tomorrow at 7pm", but I'm not sure how reliable that will be with this static build site thing-a-majig :wink:

**Comment by b1narylife** [comment]
It is a good job I am not easily offended today 😉... I will have a think / play with designs and come back to you on this point.

 > Next Thursday at 7pm", "Tomorrow at 7pm", but I'm not sure how reliable that will be with this static build site thing-a-majig
I don't think there are any issues as far as I know, Gatsby uses something similar for their yearly copyright tag but I will again check and come back to you.

**Comment by b1narylife** [comment]
I can not find a nice way of presenting the 'countdown timer' so I instead decided to take a stab at the "human readable" timestamps. PR here: https://github.com/NorfolkDev/norfolkdevelopers-website/pull/57

Lemme know if something is wrong and I will get it sorted!
