### ISSUE TITLE
External links open in the same window and replace actual site

### ISSUE THREAD

**Issue by hamza1886** [NorfolkDev/norfolkdevelopers-website#47]
External link should open in new window so that it does not replace actual site the user is visiting.

*Reproduce issue*
A user click on Discord link anywhere on site and site is gone to Discord page.

*Solution*
Here is code snippet which solves the problem by adding `target="_blank"` attribute to all links which are external to actual site.

```javascript
document.querySelectorAll('a').forEach(function (el, key, parent) {
    if (el.hasAttribute('href') && !el.getAttribute('href').search(/^https?:\/\//)) {
        el.target = '_blank';
    }
});
```

Now, I'm not sure where to add this script.

**Comment by Illizian** [comment]
> filling in a form or doing something where their work would be lost

ah, this is a good example... I think the other is a video is playing on page? I'm not sure I like the idea of updating the targets everytime a user plays and pauses though :thinking:

**Comment by TheHacksaw** [comment]
I think that's probably fine 😁 If the user is watching a video and they're able to scrub the playhead then that would be OK. I wouldn't overthink it too much 😄

**Comment by hamza1886** [comment]
I get it. It's more of a UX and standards compliance thing.
Nice use-cases discussed on https://css-tricks.com/use-target_blank/. Thanks for plugging it @Illizian 

Looks like I learned something new thing here.

This issue may be closed I guess.
